server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: SHUBHAM68
    driver-class-name: org.postgresql.Driver  # Ensure PostgreSQL driver is specified

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Corrected indentation and value


  application:
    name: Hotel-Service


  config:
    import: "optional:configserver:http://localhost:8087"
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8085/eureka/
#
#  instance:
#    prefer-ip-address: true
