server:
  port: 8081


spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: SHUBHAM68
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-Service

#This is the config server importing from the config-server
  config:
    import: "optional:configserver:http://localhost:8087"

#  profiles:
#    active: dev
       #this will activate the production or development  file i.e - application.prod




#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8085/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#
#  instance:
#    prefer-ip-address: true


#resilience4j configuration
management:
  health:
    circuitbreakers:
      enabled: true

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health


resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 3s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s
