server:
  port: 8081


spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: SHUBHAM68
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-Service



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true